### ISSUE TITLE
connecting rc receiver

### ISSUE THREAD

**Issue by awright424** [mirkix/BBBMINI#11]
Mirko,
 I was looking at the pdf for the bbbmini schematic and noticed the resistors that were attached to rc input. Is this to act as a logic level shifter? How should i go about using connecting a receiver to  a 1.2 board?

**Comment by mirkix** [comment]
Alex, it depends on which RC receiver do you use. If it is a 3.3Volt receiver, you can connect the output direct to the input of the Rev 1.2. If you are using a 5V RC receiver, you have to use a 5V to 3.3V level converter, or try something like in the Rev 1.4 (voltage divider).
