### ISSUE TITLE
Receiver question

### ISSUE THREAD

**Issue by juvinski** [mirkix/BBBMINI#12]
Hi All,

one question - it's not clear to me until now is about the receiver.
What kind of receiver can be used? PPM or PWM will work? On the board there are one RC_Input with Voltage Divider and another 3 inputs with X_Quad name and I couldn't figured out what is the purpose.

Regards

**Comment by awright424** [comment]
Need one with ppm sum, cppm or sbus. I use a orangerx r620x connected to bind port

**Comment by juvinski** [comment]
Hi, 
This part for me is a little hard.
I have 2 turnigy receivers, 2 dsm2 and one openrls(http://www.hobbyking.com/hobbyking/store/__27096__OrangeRx_Open_LRS_433MHz_9Ch_Receiver.html)
One of this can work?
Thanks

**Comment by earsneyes** [comment]
@juvinski PPM or SBUS should work. I successfully tested an Orange 7 Channel DSM2 and a FrySky X8R SBUS receiver. 

The RC_1, RC_2 and RC_4 pins are the outputs needed for a quadcopter. 
Only the RC input will work with the receiver so no PWM input.

Cheers

**Comment by awright424** [comment]
If your receiver doesn't do ppm sbus you can get a ppm encoder. But a receiver that does sbus cppm or ppm will be better.

**Comment by mirkix** [comment]
@juvinski 
For a connector description look here: https://github.com/mirkix/BBBMINI-PCB#connector .

**Comment by juvinski** [comment]
Hi Mirko,
great, now is more clear, except by one thing, P15, P16  and P17 are the motors output for X Quad, but they are for motors, 1, 3 and 4, and how about motor 2 ?

**Comment by mirkix** [comment]
<img width="402" alt="rc2" src="https://cloud.githubusercontent.com/assets/10398007/9065999/69c1c3a6-3ad5-11e5-8b23-86a10963ccc5.png">

**Comment by juvinski** [comment]
Sorry
