### ISSUE TITLE
powering and sensing battery current and voltage.

### ISSUE THREAD

**Issue by awright424** [mirkix/BBBMINI#13]
i have some questions. I have purchased this, http://www.ebay.com/itm/141729072661, power module to power my beaglebone black. I purchased it due to the fact that it does battery measurement and current sensing. Can this be made to be used with bbbmini?

**Comment by mirkix** [comment]
I started a project two day ago. It is a small digispark module connected to the i2c port of the bbbmini. The digispark board is connected to the power module you have and will report voltage and current to the bbbmini. I think it will take about a month to get it working.

**Comment by awright424** [comment]
cool. i got it in today and wouldnt mind testing that as well.
