### ISSUE TITLE
compass needs to be recalibrated all the time

### ISSUE THREAD

**Issue by awright424** [mirkix/BBBMINI#16]
I am not sure why i have to calibrate my compass every time i try to fly and half the time i cant get it to work properly. Is the resistor on the board for the compass? or is that for the canbus items? I am just not sure why i am forced to constantly re-calibrate the compass when i want to fly. BTW when it is calibrated it flies well. I need to do some tuning and get some fpv going with an android application. But after looking at how far I was able to get it I am wondering how to handle long range wifi.

**Comment by earsneyes** [comment]
Not sure why you need to recalibrate each time. You are using a external compass i guess ? 
For the range i will be using a patch antenna and a wifi router.

**Comment by awright424** [comment]
examples of antenna and type of router? And no I am not using an external compass the one that is on the board itself.

**Comment by juvinski** [comment]
Hi Alex,

It's possible interference?
Have you testes the board off the quad ?

**Comment by awright424** [comment]
this is with the beaglebone black being powered through a 5v adapter as well. I am wondering if I need to try to compensate for the motors or anything.

**Comment by earsneyes** [comment]
Im using a Fonera router with dd-wrt and a supplied antenna. They are not manufactured/sold anymore i think. 

![fon-fonera-2-0-wlan-router](https://cloud.githubusercontent.com/assets/875876/9579184/d97979de-4ff0-11e5-8df8-cac302f70128.jpg)

![fontenna_patch](https://cloud.githubusercontent.com/assets/875876/9579189/ea68658e-4ff0-11e5-8809-bd1925721e09.jpg)

**Comment by awright424** [comment]
what would you be using on the quad?

**Comment by earsneyes** [comment]
I have a TP-LINK TL-WN727N wifi dongle but can not recommend it because it was little bit of a pain to get it working.
