### ISSUE TITLE
gps

### ISSUE THREAD

**Issue by awright424** [mirkix/BBBMINI#17]
so I have this gps, https://goo.gl/photos/A2TdszUf7XFuapvy7, how do you recommend I connect it to the cape? Will there be any revisions that will support standard connections?

**Comment by mirkix** [comment]
@awright424 You have to connect the GPS RX to the BBBMINI TX and the GPS TX to the BBBMINI RX. Also GND has to be connected to GND. Make sure the GPS TX is a 3.3 Volt signal. 2.54mm pin header are the BBBMINI standard connections :-)
