### ISSUE TITLE
can you chenge aiopru pwm to 300hz or higt

### ISSUE THREAD

**Issue by cudnn** [mirkix/BBBMINI#22]
i see PWM_FREQ_DEFAULT is 50 hz ，may i chenge it to 300 or 400 and so on.

but i see  it no possobal.can you re write the aiopru.

**Comment by mirkix** [comment]
@cudnn Why it is not possible? You can change the frequency in user space with `set_freq` (https://github.com/diydrones/ardupilot/blob/master/libraries/AP_HAL_Linux/RCOutput_AioPRU.cpp#L67)
