### ISSUE TITLE
Flash process using bmaptool

### ISSUE THREAD

**Issue by jadonk** [mirkix/BBBMINI#25]
Flashing is much faster if you use 'bmaptool' if you are flashing from a Linux host, rather than using 'dd'. Robert publishes .bmap files.

**Comment by mirkix** [comment]
@jadonk Hi Jason,
unfortunately Ubuntu 14.04 LTS (which many people use) come with `bmaptool` version 2.5 and does not support .bmap files Robert publish (bmap format version 2). Maybe it is to complicated to install a newer `bmaptool`. But we can switch to `bmaptool`is there is Ubuntu 16.04 LTS, or is it possible to provide .bmap files in version 1?
