### ISSUE TITLE
PRU Compiler

### ISSUE THREAD

**Issue by juvinski** [mirkix/BBBMINI#34]
Hi,

after try this last tutorial, the PRU Compiler is missing

**Comment by mirkix** [comment]
@juvinski I have removed the PRU Compiler because the binary is in ArduPilot included.

**Comment by juvinski** [comment]
hi @mirkix,
I was following the last tutorial, but rangefinder was not compiled, the problem was  missing the compiler.
I had to install using apt-get and was failing, this was just solved after reboot the BBB.

**Comment by mirkix** [comment]
@juvinski There is no instruction to compile the rangefinder firmware. Just ```sudo make install``` is left which copies the file into the right location.
