### ISSUE TITLE
Mission planner doesn't display full parameter list

### ISSUE THREAD

**Issue by nikola-v** [mirkix/BBBMINI#36]
Hi all, 

installed ArduPlane-3.7.1 and Mission Planner 1.3.43. After syncing through Mavlink there is no Full Parameter list page in Mission Planner. Whole installation and setup was done from the tutorial (https://github.com/mirkix/BBBMINI/blob/master/doc/software/software.md).

**Comment by mirkix** [comment]
@nikola-v what kind of connection do you use?

**Comment by nikola-v** [comment]
@mirkix  I have tried both UDP and Serial. 
There is no option like in the picture (random google searched pic)
 http://ardupilot.org/copter/_images/RangeFinder_LIDARLite_MPSetup.png
Should I have that option ?

**Comment by mirkix** [comment]
http://diydrones.com/forum/topics/mission-planner-1-3-42-no-full-parameters-list

**Comment by nikola-v** [comment]
Thank you mirkix!
