### ISSUE TITLE
Handling Interrupt

### ISSUE THREAD

**Issue by AmirhosseinR** [mirkix/BBBMINI#39]
Hello Denecke;
Thanks for sharing your interesting project. I have one question about Linux embedded programming. How do you handle hard interrupt? For Example external interrupt that comes from MPU-9250:
1- By Polling GPIO in Linux user space (c code and thread)
2- By using PRU (poll GPIO and send soft interrupt to Linux USER SPACE)
3- Linux Kernel Programming (Which support hard interrupt)
Or we can do it in RT-Linux by programing USER SPACE
Yours Sincerely,
Rostami;

**Comment by mirkix** [comment]
@AmirhosseinR I can't help here. BBBmini does not use the INT pin yet.
