### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by adricl** [mirkix/BBBMINI#40]
Hello, 

When following the instructions on the build on the software installation I get the following:

`
Unpacking linux-image-4.4.73-bone-rt-r18 (1jessie) ...
Setting up linux-image-4.4.73-bone-rt-r18 (1jessie) ...
update-initramfs: Generating /boot/initrd.img-4.4.73-bone-rt-r18
cp: cannot stat '/etc/modprobe.d/*': No such file or directory
zz-uenv_txt: Updating /boot/uEnv.txt [uname_r=4.4.73-bone-rt-r18]
`

This also happened when I was doing the upgrade. The BBB seems to reboot and work fine, but I am not sure what exactly is causing this issue. The /etc/modprobe.d exits.

Thanks,

**Comment by juvinski** [comment]
Hi @adricl,

I have the same error, but there is nothing to worry about, the BBBMini will work.
