### ISSUE TITLE
Request to provide the libraries being used

### ISSUE THREAD

**Issue by Thalaivar** [mirkix/BBBMINI#43]
This was such a lovely project and I built one of these myself! I request you to tell me which libraries you used and provide me any that you wrote yourself for the sensors, RC, UART etc. I have been hunting everywhere for them and I have only found your PRU firmware on hackster.io

**Comment by mirkix** [comment]
All libraries are part of ArduPilot, you can take a look at https://github.com/ArduPilot/ardupilot .

Regards
Mirko
